name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: welch-lab/actions-eleventy@master
        with:
          install_dependencies: true
        env:
          CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
          CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}
                    
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@v1.4.0
        with:
          input: src/style/base.css
          output: _site/output.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: homekit.cam
            
